name: Swift
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      
      - name: Trust GitHub SSH keys
        run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
          
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa 
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use latest Swift version
        uses: fwal/setup-swift@v1
        
      - name: Build
        run: swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios15.4-simulator"
